apiVersion: apps/v1 ## version de la api para deployment
kind: Deployment    ## tipo de recurso u objeto que se va a crear
metadata:           ## metadatos del deployment 
  name: apache-deployment ## nombre del deployment
  namespace: frontend
  labels:           ## etiquetas para identificar el deployment
    app: apache-app  ## etiqueta clave-valor
    environment: desarrollo
spec:          ## especificacion del deployment
  replicas: 3
  selector:
    matchLabels:
      app: apache-app
      environment: desarrollo
  template:
    metadata:
      labels:
        app: apache-app
        environment: desarrollo
    spec:
      containers:
      - name: apache-container ##--> listas de contenedores dentro del pod
        image: nginx:latest
        ports:
        - containerPort: 80