apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    app: apache-app
    environment: desarrollo
spec:
  type: LoadBalancer
  selector:
    app: apache-app
    environment: desarrollo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80